package com.example.springkafka.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;

@Schema(description = "Represents an enriched order event generated by joining KStream with KTable in real time")
public record EnrichedOrderEvent(
        @Schema(description = "Order ID", example = "ORD-98721")
        String orderId,

        @Schema(description = "Customer ID", example = "CUST-4501")
        String customerId,

        @Schema(description = "SKU Code", example = "SKU-LAPTOP-X1")
        String skuCode,

        @Schema(description = "Ordered item name joined from inventory KTable", example = "Ultrabook Pro 16")
        String itemName,

        @Schema(description = "Warehouse code joined from inventory KTable", example = "WH-US-EAST-1")
        String warehouseCode,

        @Schema(description = "Quantity ordered", example = "2")
        int quantity,

        @Schema(description = "Unit price", example = "1299.99")
        double price,

        @Schema(description = "Total cost (price * quantity)", example = "2599.98")
        double totalCost,

        @Schema(description = "Order priority", example = "HIGH")
        String priority,

        @Schema(description = "Enrichment timestamp")
        String enrichedAt
) {
    public static EnrichedOrderEvent of(OrderEvent order, InventoryItem item) {
        String itemName = (item != null) ? item.itemName() : "UNKNOWN_ITEM";
        String wh = (item != null) ? item.warehouseCode() : "DEFAULT_WAREHOUSE";
        double total = order.price() * order.quantity();
        return new EnrichedOrderEvent(
                order.orderId(),
                order.customerId(),
                order.skuCode(),
                itemName,
                wh,
                order.quantity(),
                order.price(),
                total,
                order.priority(),
                Instant.now().toString()
        );
    }
}
